config/routes.rb
StockTrendFinder::Application.routes.draw do
  resources :tweets
  resources :tickers
  resources :stocktwits, except: [:show]
  # Stocktwits AJAX calls
  post 'stocktwits/add_twit'        => 'stocktwits#add_twit'
  post 'stocktwits/edit_twit'       =>'stocktwits#edit_twit'
  post 'stocktwits/call_result'     => 'stocktwits#call_result'
  post 'stocktwits/hide'            => "stocktwits#hide"
  post 'stocktwits/load_twits'      => "stocktwits#load_twits"
  # post 'stocktwits/note'            => 'stocktwits#edit_note'
  get 'stocktwits/refresh'          => "stocktwits#refresh"
  get 'stocktwits/toggle_watching'  => "stocktwits#toggle_watching"
  get 'stocktwits/watching'         => "stocktwits#watching"

  namespace :reports do
    get 'active_stocks'
    get 'range'
    get 'premarket'
    get 'gaps'
    get 'afterhours'
    get 'earnings'
    get 'sma50_breaks'
    get 'sma200_breaks'
    get 'candle_row'
    get 'pctgainloss'
    get 'week52_highs'
    get 'week52_lows'
    get 'ticker_list'
    get 'ipo_list'
    get 'reviewed_reports'
    patch 'mark_reviewed'
  end
  patch 'reports/hide/:symbol(.:format)', to: 'reports#hide_symbol', as: 'reports_hide_symbol'
  patch 'reports/unscrape/:symbol(.:format)', to: 'reports#unscrape_symbol', as: 'reports_unscrape_symbol'
  post 'tickers/:ticker/note', to: 'tickers#note', as: 'tickers_note'

  namespace :tda_data do
    post 'watchlists/symbol', to: 'watchlists#add_symbol', as: 'watchlists_add_symbol'
  end

  root 'home#index'
end

app/models/stocktwit.rb
require 'stocktwits_api'

class Stocktwit < ActiveRecord::Base
  FIRST_TWIT_ID=18772403
  ATTEMPTS=3

  has_many :stocktwit_tickers # Keeping this separate from the Tickers table because there may be tickers encountered on ST not in the table
  has_many :stocktwit_hashtags

  enum call_result: { no_call: 0, correct: 1, incorrect: 2, partial: 3 }

  scope :showing, -> (user_id='greenspud') { where(hide: false, stocktwits_user_name: user_id) }

  def self.rename_symbol(old_symbol, new_symbol)
    Stocktwit.where(symbol: old_symbol).update_all(symbol: new_symbol)
    StocktwitTicker.where(ticker_symbol: old_symbol).update_all(ticker_symbol: new_symbol)
    StocktwitWatchTicker.where(ticker_symbol: old_symbol).update_all(ticker_symbol: new_symbol)
  end

  def self.ticker_list(order_by='ticker_symbol', user_id='greenspud')
    ActiveRecord::Base.connection.execute(ticker_list_sql(order_by, user_id))
  end

  def self.setup_list
    StocktwitHashtag.group(:tag).count(:tag).sort { |tag_a, tag_b| tag_b[0] <=> tag_a[0] }
  end

  def self.watching_list
    ActiveRecord::Base.connection.execute(watching_list_sql)
  end

  def self.watching?(symbol)
    StocktwitWatchTicker.find_by(ticker_symbol: symbol).present? && StocktwitWatchTicker.find_by(ticker_symbol: symbol).watching?
  end

  def self.toggle_watching(symbol)
    swt = StocktwitWatchTicker.find_by(ticker_symbol: symbol)
    if swt.present?
      swt.update(watching: !swt.watching)
    else
      swt = StocktwitWatchTicker.create(ticker_symbol: symbol, watching: true)
    end
    @result = swt.watching
  end

  def parse_hashtags!
    message.scan(/(?:\s)(#\S*)/).each do |hashtag|
      hashtag = hashtag.first
      stocktwit_hashtags.create(tag: hashtag) if stocktwit_hashtags.find_by(tag: hashtag).nil?
    end
  end

private

  def self.ticker_list_sql(order_by, user_id)
    <<SQL
    select tx.ticker_symbol, current_date - date_trunc('day', max(stocktwit_time)) as last_updated, max(stocktwit_time) as last_updated_date, count(st.symbol) as count, coalesce(watching, false) as watching
    from stocktwit_tickers tx 
    inner join stocktwits st on tx.stocktwit_id=st.id
    left join stocktwit_watch_tickers tw on tw.ticker_symbol=tx.ticker_symbol
    where
    stocktwits_user_name='#{user_id}' and
    st.hide=false
    group by tx.ticker_symbol, watching
    order by #{order_by}
SQL
  end

  def self.watching_list_sql
    <<SQL
    select swt.ticker_symbol, swt.watching, current_date - date_trunc('day', max(stocktwit_time)) as last_updated, count(st.ticker_symbol)
    from stocktwit_watch_tickers swt inner join stocktwit_tickers st on swt.ticker_symbol=st.ticker_symbol
    inner join stocktwits s on s.id=st.stocktwit_id
    where swt.watching
    group by swt.ticker_symbol, swt.watching
    order by last_updated
SQL
  end
end

app/controllers/stocktwits_controller.rb
class StocktwitsController < ApplicationController
  layout "stocktwits"
  before_action :user_id, :ticker_symbol

  def index
    unless ticker_symbol.present?
      @twits = Stocktwit.showing(@user_id).order(stocktwit_date: :desc, id: :desc).limit(20)
    else
      # If we have a ticker param, don't load any because the Javascript will load the page
      @twits = Stocktwit.none
    end

    ticker_list = Stocktwit.ticker_list('ticker_symbol', @user_id)
    @ticker_list_symbol = ticker_list.to_a
    @ticker_list_count = @ticker_list_symbol.sort { |a,b| b['count'].to_i <=> a['count'].to_i }
    @ticker_list_updated = @ticker_list_symbol.sort { |a,b| b['last_updated_date'] <=> a['last_updated_date'] }
    @ticker_list_watching = Stocktwit.watching_list

    @setup_list = Stocktwit.setup_list
  end

  def load_twits
    maxtwit = Stocktwit.select(:id, :stocktwit_date, :stocktwit_time).find(params[:max]) if params[:max].present?

    @twits = Stocktwit.showing(@user_id)
    @twits = @twits.where("stocktwits.stocktwit_date <= ?", maxtwit.stocktwit_date) if params[:max].present?
    @twits = @twits.where(symbol: ticker_symbol) if ticker_symbol.present?
    @twits = @twits.joins(:stocktwit_hashtags).where(stocktwit_hashtags: {tag: params[:setup]}) if params[:setup].present?
    @twits = @twits.order(stocktwit_date: :desc, id: :desc)
    @twits = @twits.limit(20)

    if @twits.length == 0
      render status: :ok, layout: false
    else
      render "load_twits", layout: false
    end
  end

  def add_twit
    head :bad_request  if params[:message].nil?
    outcome, @twit = LocalNoteTaker::CreateStocktwitNoteWithScreenshot.(
      note: params[:message],
      stocktwit_time: params[:followup_id].present? ? Stocktwit.find(params[:followup_id]).stocktwit_time + 60 : Time.now,
      screen_count: screen_count || 2
    )

    if outcome == :ok
      render 'twit_result_ok'
    else
      render 'twit_result_error'
    end
  end

  def edit_twit
    head :bad_request if params[:message].nil?
    outcome, @twit = LocalNoteTaker::EditStocktwit.(
      stocktwit_id: params[:id],
      message: params[:message]
    )

    if outcome == :ok
      render 'edit_twit_ok'
    else
      render 'edit_twit_error'
    end
  end

  def edit_note
    head :bad_request  if params[:note].nil? || params[:id].nil?
    if @twit = Stocktwits::AddNote.(stocktwit_id: params[:id], note_message: params[:note])
      render 'note_result_ok'
    else
      render 'note_result_error'
    end
  end

  def refresh
    Stocktwit.sync_twits
    redirect_to stocktwits_path
  end

  def toggle_watching
    symbol = params[:symbol]
    @result = Stocktwit.toggle_watching(symbol)
    render status: :ok
  end

  def watching
    symbol = params[:symbol]
    @result = { watching: Stocktwit.watching?(symbol) }
    render json: @result
  end

  def call_result
    head :bad_request  if params[:call_result].nil? || params[:id].nil?
    @twit = Stocktwit.find(params[:id])
    if @twit.update(call_result: params[:call_result])
      render 'call_result_ok'
    else
      render 'call_result_error'
    end
  end

  def hide
    head :bad_request if params[:id].nil?
    @twit = Stocktwit.find(params[:id])
    @twit.update(hide: true)
  end

private
  TICKER_SYMBOL_ALIASES = [%w(SPY SPXL SSO), %w(VXX VXXB XIV SVXY)]

  def ticker_symbol
    return @ticker_symbol if @ticker_symbol.present?

    ticker_raw = params[:symbol].to_s.strip
    aliases = TICKER_SYMBOL_ALIASES.select { |a| a.include?(ticker_raw) }.flatten
    @ticker_symbol = aliases.any? ? aliases : ticker_raw
  end

  def screen_count
    params[:screen_count] =~ /1/ ? 1 : 2
  end

  def user_id
    @user_id = params[:user_id] || 'greenspud'
  end
end

app/helpers/stocktwits_helper.rb
require 'htmlentities'

module StocktwitsHelper

  def format_setup_nav_link(setup)
    "#{link_to(setup[0], "#", :class=>"setup-filter-link", "data-setup"=>setup[0])} (#{setup[1]})"
  end

  def format_stocktwits_message(message_text)
    format_links(message_text)
  end

  def format_ticker_nav_link(ticker)
    last_updated = ticker['last_updated'] == '00:00:00' ? 'Today' : ticker['last_updated']
    watching_icon = ticker['watching']=='t' ? "\u2606" : ''
    "#{link_to(ticker['ticker_symbol'], "#", :class=>"symbol-filter-link", "data-symbol"=>ticker['ticker_symbol'])} #{watching_icon}(#{ticker['count']}) - #{last_updated}"
  end

  def message_call_result_class(call)
    case call
      when 'correct'
        "message-call-result-correct"
      when 'incorrect'
        "message-call-result-incorrect"
      when 'no_call'
        "message-call-result-no-call"
      when 'partial'
        "message-call-result-partial"
      else
        ""
    end
  end

  private


  def convert_links(s)
    # convert link text to links
    m = s.match /\bhttp:\/\/.*\b/
    if m
      s.sub(m[0], link_to(m[0], m[0], target: "_blank"))
    else
      s
    end

    # convert ticker symbols to links
    m = s.match /^\$*[A-Z]+/
    if m
      symbol = m[0].gsub('$', '')
      s.sub(m[0], link_to(m[0], "#", class: 'no-decoration symbol-filter-link', 'data-symbol'=>m[0]))
    else
      s
    end
  end

  def format_links(message_text)
    coder = HTMLEntities.new
    raw(convert_links(coder.decode(message_text)))
  end

end

app/views/stocktwits/_call_result_buttons.html.haml
.message-call-result-buttons{ "data-twit-id": twit.id }
  = raw("#{link_to(image_tag('icon-thumbsup50x50.png'), stocktwits_call_result_path(id: twit.id, call_result: 'correct'), remote: true, method: :post)} #{link_to(image_tag('icon-partial50x50.png'), stocktwits_call_result_path(id: twit.id, call_result: 'partial'), remote: true, method: :post)} #{link_to(image_tag('icon-thumbsdown50x50.png'), stocktwits_call_result_path(id: twit.id, call_result: 'incorrect'), remote: true, method: :post)} | #{link_to(image_tag('icon-info-50x50.png'), stocktwits_call_result_path(id: twit.id, call_result: 'no_call'), remote: true, method: :post)} | #{link_to(image_tag('icon-hide50x50.png'), stocktwits_hide_path(id: twit.id), remote: true, method: :post)} | #{image_tag('icon-note50x50.png', class: "icon-note", style: "cursor: pointer;", "data-toggle": "modalNote", "data-target": "#modalNote")} | #{image_tag('icon-followup50x50.png', class: "icon-followup", style: "cursor: pointer;", "data-toggle": "modalFollowup", "data-target": "#modalFollowup")}")

app/views/stocktwits/_load_twits_script.html.haml
:coffee
  loading = false
  nomore = false

  $last_twit_id = () -> $('table.stocktwits tr').filter(':last').attr('id')
  $symbol_filter = () -> $('#stocktwits-filter-indicator').attr('data-symbol')
  $setup_filter = () -> $('#stocktwits-filter-indicator').attr('data-setup')
  $setup_or_symbol_filter = () -> $('#stocktwits-filter-indicator').text()
  -#$user_id_filter = () -> $('#user-dropdown-button').text().trim()
  $user_id_filter = "greenspud"

  #  http://www.jquerybyexample.net/2012/06/get-url-parameters-using-jquery.html
  getUrlParameter = (sParam) ->
    sPageURL = decodeURIComponent(window.location.search.substring(1))
    sURLVariables = sPageURL.split('&')
    for sURLVariable in sURLVariables
      sParameterName = sURLVariable.split('=')
      if sParameterName[0] == sParam
        if sParameterName[1] == undefined
          return false
        else
          return sParameterName[1]

  load_next = (symbol_or_setup, last_id) ->
    loading = true

    -#console.log symbol_or_setup
    -#console.log symbol_or_setup[0] == '#'
    if symbol_or_setup[0] == '#'
      postdata = { user_id: $user_id_filter, setup: symbol_or_setup, max: last_id }
    else
      postdata = { user_id: $user_id_filter, symbol: symbol_or_setup, max: last_id }

    $('.last-twit-placeholder').show()
    $.post '/stocktwits/load_twits' \
      , postdata \
      , (data) ->
        if data.length > 0
           if $('table.stocktwits tr').filter(':last').length > 0
             jData = $.parseHTML(data)
             jData.forEach (el) ->
               if el.nodeName == 'TR' && $('table.stocktwits tr#' + el.getAttribute('id')).html() == undefined
                 $('table.stocktwits tr').filter(':last').after(el.outerHTML)
           else
             $('table.stocktwits').append(data)
        else
          nomore = true
        $('.last-twit-placeholder').hide()
        loading = false

  set_symbol_filter = (symbol) ->
    $('#stocktwits-content table.stocktwits').empty()
    $('#stocktwits-filter-indicator').attr('data-symbol', symbol)
    $('#stocktwits-filter-indicator').text(symbol)
    nomore = false
    load_next($symbol_filter(), null)

  set_setup_filter = (setup) ->
    $('#stocktwits-content table.stocktwits').empty()
    $('#stocktwits-filter-indicator').attr('data-setup', setup)
    $('#stocktwits-filter-indicator').text(setup)
    nomore = false
    load_next($setup_filter(), null)

  set_watching_icon = () ->
    $.getJSON '/stocktwits/watching.json', {symbol: $symbol_filter}, (data) ->
      if data.watching
        $('img.stocktwits-watch-indicator').attr('src', '/assets/icon-star-sm-yellow.png')
      else
        $('img.stocktwits-watch-indicator').attr('src', '/assets/icon-star-sm-grey.png')
      $('img.stocktwits-watch-indicator').show()

  $('a.symbol-filter-link').click () ->
    symbol = $(this).attr('data-symbol')
    set_symbol_filter(symbol)
    set_watching_icon()
    false

  $('a.setup-filter-link').click () ->
    set_setup_filter($(this).attr('data-setup'))
    set_watching_icon()
    false

  $('a#toggle-watching').click () ->
    console.log($.get('/stocktwits/toggle_watching', {symbol: $symbol_filter}))
    set_watching_icon()
    false

  $(window).scroll () ->
    if $(window).scrollTop() >= $('#stocktwits-content').height() - $(window).height() - 500
      if !loading && !nomore
        load_next($setup_or_symbol_filter(), $last_twit_id)

  $ ->
    symbol = getUrlParameter('symbol')
    if symbol != undefined
      set_symbol_filter(symbol)
      set_watching_icon()

app/views/stocktwits/_note_dialog.html.haml
-# Decided not to use this route in favor of a simple javascript prompt box
-#
-#.modal-dialog{ role: "document" }
-#  .modal.fade{ tabindex: "-1", role: "dialog", "aria-labelledby": "myModalLabel", id: "modalNote" }
-#    .modal-content
-#      .modal-header
-#        %button.close{ type: "button", "data-dismiss": "modal", "aria-label": "Close" }
-#          %span{ "aria-hidden": "true" }
-#            &times;
-#        -#%h4{ class: "modal-title" }
-#        -#  Edit Comment
-#      .modal-body
-#        Greetings lorem ipsum
-#      .modal-footer
-#        %button{ type: "button", class:"btn btn-default", "data-dismiss":"modal"} Close
-#        %button{ type: "button", class: "btn btn-primary"}Save changes

app/views/stocktwits/_setup_navigation.html.haml
%h3 Setups

.stocktwits-setup-nav-list#count
  -@setup_list.each do |setup|
    .stocktwits-setup-nav-link
      = format_setup_nav_link(setup).html_safe

app/views/stocktwits/_ticker_navigation.html.haml
%h3 Tickers

.stocktwits-ticker-nav-filter
  = raw("#{link_to('Symbol', '#', id: 'stocktwits-ticker-nav-filter-symbol')} | #{link_to('Count', '#', id: 'stocktwits-ticker-nav-filter-count')} | #{link_to('Updated', '#', id:'stocktwits-ticker-nav-filter-updated')} |  #{link_to('Watching', '#', id:'stocktwits-ticker-nav-filter-watching')}")

.stocktwits-ticker-nav-list#symbol
  -@ticker_list_symbol.each do |ticker|
    .stocktwits-ticker-nav-link
      = format_ticker_nav_link(ticker).html_safe

.stocktwits-ticker-nav-list#count
  -@ticker_list_count.each do |ticker|
    .stocktwits-ticker-nav-link
      = format_ticker_nav_link(ticker).html_safe

.stocktwits-ticker-nav-list#updated
  -@ticker_list_updated.each do |ticker|
    .stocktwits-ticker-nav-link
      = format_ticker_nav_link(ticker).html_safe

.stocktwits-ticker-nav-list#watching
  -@ticker_list_watching.each do |ticker|
    .stocktwits-ticker-nav-link
      = format_ticker_nav_link(ticker).html_safe


:coffee
  $('#stocktwits-ticker-nav-filter-symbol').click () ->
    $('.stocktwits-ticker-nav-list#symbol').show()
    $('.stocktwits-ticker-nav-list#updated').hide()
    $('.stocktwits-ticker-nav-list#count').hide()
    $('.stocktwits-ticker-nav-list#watching').hide()
    false # see http://stackoverflow.com/questions/3106695/jquery-hide-method-only-hides-div-for-a-second-but-then-div-reappears-automatica for explanation of this line

  $('#stocktwits-ticker-nav-filter-count').click () ->
    $('.stocktwits-ticker-nav-list#symbol').hide()
    $('.stocktwits-ticker-nav-list#updated').hide()
    $('.stocktwits-ticker-nav-list#count').show()
    $('.stocktwits-ticker-nav-list#watching').hide()
    false # see http://stackoverflow.com/questions/3106695/jquery-hide-method-only-hides-div-for-a-second-but-then-div-reappears-automatica for explanation of this line

  $('#stocktwits-ticker-nav-filter-updated').click () ->
    $('.stocktwits-ticker-nav-list#symbol').hide()
    $('.stocktwits-ticker-nav-list#updated').show()
    $('.stocktwits-ticker-nav-list#count').hide()
    $('.stocktwits-ticker-nav-list#watching').hide()
    false # see http://stackoverflow.com/questions/3106695/jquery-hide-method-only-hides-div-for-a-second-but-then-div-reappears-automatica for explanation of this line

  $('#stocktwits-ticker-nav-filter-watching').click () ->
    $('.stocktwits-ticker-nav-list#symbol').hide()
    $('.stocktwits-ticker-nav-list#updated').hide()
    $('.stocktwits-ticker-nav-list#count').hide()
    $('.stocktwits-ticker-nav-list#watching').show()
    false # see http://stackoverflow.com/questions/3106695/jquery-hide-method-only-hides-div-for-a-second-but-then-div-reappears-automatica for explanation of this line

app/views/stocktwits/_toggle_single_screen_script.html.haml
:javascript
  $(document).on("click", '#screens-one-toggle', function(event) {
    event.preventDefault();
    $('#screens-dropdown-button').text('1 Screen');
  })

  $(document).on("click", '#screens-two-toggle', function(event) {
    event.preventDefault();
    $('#screens-dropdown-button').text('2 Screens');
  })

app/views/stocktwits/call_result_ok.js.erb
//$('table.stocktwits tr#<%= @twit.id %> .stocktwit-message .stocktwit-message-call-result-buttons').hide();
$('table.stocktwits tr#<%= @twit.id %> .stocktwit-message').attr('class', '<%= message_call_result_class(@twit.call_result) %>');

app/views/stocktwits/edit_twit_ok.js.erb
$('table.stocktwits tr#<%= @twit.id %> td .stocktwit-message-text').html('<%= @twit.message %>');

app/views/stocktwits/hide.js.erb
$('table.stocktwits tr#<%= @twit.id %>').hide();

app/views/stocktwits/index.html.haml
=render "note_dialog"

.col-md-9
  #header
    #title
      %h1
        =link_to('StockTwits Archive', stocktwits_path, class: 'no-decoration')
        =link_to(image_tag(asset_path('icon-cloud-download.png')), stocktwits_refresh_path)
    #user-dropdown
      .btn-group
        %button.btn.btn-default.dropdown-toggle#screens-dropdown-button{:type=> "button", "data-toggle"=>"dropdown", "aria-expanded"=>"false"}
          ="2 Screens"
        %ul.dropdown-menu{ role: "menu" }
          %li= link_to("1 Screen", "", id: "screens-one-toggle")
          %li= link_to("2 Screens", "", id: "screens-two-toggle")
  #stocktwits-watch-indicator{ "data-symbol"=>"" }
    =link_to(image_tag(asset_path('icon-star-sm-yellow.png'), class: 'stocktwits-watch-indicator', style: "display: none;"), "#", id: 'toggle-watching')
  #stocktwits-filter-indicator{ "data-symbol"=>"" }
    &nbsp;
  #stocktwits-add-twit
    %button.btn.btn-default#add-twit-button{ type: 'button' } New Note

  #stocktwits-content
    %table.stocktwits
      -@twits.each do |twit|
        =render "twit", twit: twit

  .last-twit-placeholder
    =image_tag(asset_path("loading.gif"))

.col-md-3
  .stocktwits-ticker-navigation
    = render partial: 'ticker_navigation'
  .stocktwits-setup-navigation
    = render partial: 'setup_navigation'

=render "toggle_single_screen_script"
=render "load_twits_script"
=render "edit_note_dialog_script"
=render "add_twit_dialog_script"

app/views/stocktwits/load_twits.html.haml
-@twits.each do |twit|
  =render "twit", twit: twit

app/views/stocktwits/note_result_error.js.erb
alert('Error updating the message note')

app/views/stocktwits/note_result_ok.js.erb
$('table.stocktwits tr#<%= @twit.id %> .stocktwit-message .stocktwit-message-note').html('<%= @twit.note %>');

app/views/stocktwits/twit_result_error.js.erb
alert('Error updating the message note')