config/routes.rb
StockTrendFinder::Application.routes.draw do
  resources :tweets
  resources :tickers
  resources :stocktwits, except: [:show]
  # Stocktwits AJAX calls
  post 'stocktwits/add_twit'        => 'stocktwits#add_twit'
  post 'stocktwits/edit_twit'       =>'stocktwits#edit_twit'
  post 'stocktwits/call_result'     => 'stocktwits#call_result'
  post 'stocktwits/hide'            => "stocktwits#hide"
  post 'stocktwits/load_twits'      => "stocktwits#load_twits"
  # post 'stocktwits/note'            => 'stocktwits#edit_note'
  get 'stocktwits/refresh'          => "stocktwits#refresh"
  get 'stocktwits/toggle_watching'  => "stocktwits#toggle_watching"
  get 'stocktwits/watching'         => "stocktwits#watching"

  namespace :reports do
    get 'active_stocks'
    get 'range'
    get 'premarket'
    get 'gaps'
    get 'afterhours'
    get 'earnings'
    get 'sma50_breaks'
    get 'sma200_breaks'
    get 'candle_row'
    get 'pctgainloss'
    get 'week52_highs'
    get 'week52_lows'
    get 'ticker_list'
    get 'ipo_list'
    get 'reviewed_reports'
    patch 'mark_reviewed'
  end
  patch 'reports/hide/:symbol(.:format)', to: 'reports#hide_symbol', as: 'reports_hide_symbol'
  patch 'reports/unscrape/:symbol(.:format)', to: 'reports#unscrape_symbol', as: 'reports_unscrape_symbol'
  post 'tickers/:ticker/note', to: 'tickers#note', as: 'tickers_note'

  namespace :tda_data do
    post 'watchlists/symbol', to: 'watchlists#add_symbol', as: 'watchlists_add_symbol'
  end

  root 'home#index'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  layout "stocktwits"
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new(message: converted_message, local_image_url: twit.image_cropped_url, stocktwit_id: twit.id)
  end

  # GET /tweets/1/edit
  # def edit
  # end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.valid?
      @tweet.twitter_message_id = Twitter::CreateTweet.call(tweet: @tweet).value
      @tweet.save!
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render action: :new
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  # def update
  #   respond_to do |format|
  #     if @tweet.update(tweet_params)
  #       format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @tweet.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  # def destroy
  #   @tweet.destroy
  #   respond_to do |format|
  #     format.html { redirect_to tweets_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def converted_message
      Twitter::ConvertMessage.call(message: twit.message).value
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :local_image_url, :stocktwit_id)
    end

    def twit
      @twit ||= Stocktwit.find(params[:stocktwit_id]) || OpenStruct.new()
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div><%= f.text_area(:message, style: "width: 800px;") %></div>

  <div><%= image_tag(@tweet.local_image_url, style: "width: 800px") %></div>
  <%=f.hidden_field :local_image_url %>
  <%=f.hidden_field :stocktwit_id %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>