config/routes.rb
StockTrendFinder::Application.routes.draw do
  resources :tweets
  resources :tickers
  resources :stocktwits, except: [:show]
  # Stocktwits AJAX calls
  post 'stocktwits/add_twit'        => 'stocktwits#add_twit'
  post 'stocktwits/edit_twit'       =>'stocktwits#edit_twit'
  post 'stocktwits/call_result'     => 'stocktwits#call_result'
  post 'stocktwits/hide'            => "stocktwits#hide"
  post 'stocktwits/load_twits'      => "stocktwits#load_twits"
  # post 'stocktwits/note'            => 'stocktwits#edit_note'
  get 'stocktwits/refresh'          => "stocktwits#refresh"
  get 'stocktwits/toggle_watching'  => "stocktwits#toggle_watching"
  get 'stocktwits/watching'         => "stocktwits#watching"

  namespace :reports do
    get 'active_stocks'
    get 'range'
    get 'premarket'
    get 'gaps'
    get 'afterhours'
    get 'earnings'
    get 'sma50_breaks'
    get 'sma200_breaks'
    get 'candle_row'
    get 'pctgainloss'
    get 'week52_highs'
    get 'week52_lows'
    get 'ticker_list'
    get 'ipo_list'
    get 'reviewed_reports'
    patch 'mark_reviewed'
  end
  patch 'reports/hide/:symbol(.:format)', to: 'reports#hide_symbol', as: 'reports_hide_symbol'
  patch 'reports/unscrape/:symbol(.:format)', to: 'reports#unscrape_symbol', as: 'reports_unscrape_symbol'
  post 'tickers/:ticker/note', to: 'tickers#note', as: 'tickers_note'

  namespace :tda_data do
    post 'watchlists/symbol', to: 'watchlists#add_symbol', as: 'watchlists_add_symbol'
  end

  root 'home#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/reports_controller.rb
require 'tdameritrade_data_interface/tdameritrade_data_interface'

class ReportsController < ApplicationController
  include Reports::Build::SQL

  def active_stocks
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :volume,
      :volume_average,
      :volume_ratio,
      :short_days_to_cover,
      :short_percent_of_float,
      :float,
      :float_percent_traded,
      :dividend_yield,
      :institutional_ownership_percent,
      :index,
      :actions
    ]
    line_items = Reports::Build::Active.call(report_date: report_date).value
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: line_items, sort_field: sort_field, sort_direction: :desc).value

    @report = {
      title: 'Active Stocks Report',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::Active.(report: sorted_line_items).value,
      route: :active_stocks,
    }

    render :report
  end

  def afterhours
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :volume,
      :volume_average,
      :volume_ratio,
      :short_days_to_cover,
      :short_percent_of_float,
      :float,
      :float_percent_traded,
      :dividend_yield,
      :institutional_ownership_percent,
      :index,
      :actions
    ]

    line_items = Reports::Build::AfterHours.call(report_date: report_date).value
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: line_items, sort_field: sort_field, sort_direction: :desc).value

    @report = {
      title: 'After Hours Report',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::AfterHours.(report: sorted_line_items).value,
      route: :afterhours,
    }

    render :report
  end

  def gaps
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :gap_percent,
      :volume,
      :volume_average,
      :volume_ratio,
      :short_days_to_cover,
      :short_percent_of_float,
      :float,
      :float_percent_traded,
      :dividend_yield,
      :institutional_ownership_percent,
      :index,
      :actions
    ]

    line_items = Reports::Build::Gaps.call(report_date: report_date).value
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: line_items, sort_field: sort_field, sort_direction: :desc).value

    @report = {
      title: 'Gap Up / Gap Down Report',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::Gaps.(report: sorted_line_items).value,
      route: :gaps,
    }

    render :report
  end

  def premarket
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :volume,
      :volume_average,
      :volume_ratio,
      :short_days_to_cover,
      :short_percent_of_float,
      :float,
      :float_percent_traded,
      :market_cap,
      :dividend_yield,
      :institutional_ownership_percent,
      :outside_52_week_range,
      :index,
      :actions
    ]

    line_items = Reports::Build::Premarket.call(report_date: report_date).value
    filtered_line_items = filter(line_items)
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: filtered_line_items, sort_field: sort_field, sort_direction: :desc).value

    @report = {
      title: 'Premarket Report',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::Premarket.(report: sorted_line_items).value,
      route: :premarket,
    }

    render :report
  end

  def hide_symbol
    @symbol = params[:symbol]
    hidden_until = Actions::HideTickerFromReports.(ticker: @symbol).value
    if hidden_until.present?
      flash[:notice] = "#{@symbol} hidden until #{hidden_until}"
    else
      flash[:notice] = "#{@symbol} unhidden"
    end
  end

  def unscrape_symbol
    @symbol = params[:symbol]
    Ticker.unscrape(@symbol)
  end

  def week52_highs
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :percent_above_52_week_high,
      :volume,
      :volume_average,
      :volume_ratio,
      :week_52_streak,
      :days_active,
      :float,
      :float_percent_traded,
      :dividend_yield,
      :institutional_ownership_percent,
      :market_cap,
      :index,
      :actions
    ]

    line_items = Reports::Build::FiftyTwoWeekHigh.call(report_date: report_date).value
    filtered_line_items = filter(line_items)
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: filtered_line_items, sort_field: sort_field).value

    @report = {
      title: '52 Week High List',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::FiftyTwoWeekHigh.(report: sorted_line_items).value,
      route: :week52_highs,
      report_date: report_date,
      reviewed_date: ReportReview.report_reviewed_date(:week52_highs, report_date),
      unfiltered_item_count: line_items.size
    }

    render :report
  end

  def week52_lows
    @fields = [
      :ticker_symbol,
      :last_trade,
      :change_percent,
      :percent_below_52_week_low,
      :volume,
      :volume_average,
      :volume_ratio,
      :week_52_streak,
      :days_active,
      :float,
      :float_percent_traded,
      :market_cap,
      :dividend_yield,
      :institutional_ownership_percent,
      :index,
      :actions
    ]

    line_items = Reports::Build::FiftyTwoWeekLow.call(report_date: report_date).value
    filtered_line_items = filter(line_items)
    sorted_line_items = Reports::Presenters::LineItemSort.(line_items: filtered_line_items, sort_field: sort_field).value

    @report = {
      title: '52 Week Low List',
      last_updated: sorted_line_items.size > 0 ? sorted_line_items.first[:snapshot_time].in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S') : '',
      item_count: sorted_line_items.size,
      sections: Reports::Build::Sections::FiftyTwoWeekLow.(report: sorted_line_items).value,
      route: :week52_lows,
      unfiltered_item_count: line_items.size
    }

    render :report
  end

  def ticker_list
    line_items = Reports::Build::TickerList.call(report_date: report_date).value

    @report = {
      title: 'Master Ticker List',
      last_updated: Time.current.in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S'),
      line_items: line_items,
      item_count: line_items.size,
    }

    render :ticker_list_report
  end

  def industry
    line_items = Reports::Build::Industry.call(report_date: report_date).value

    ### INCOMPLETE - NOT READY YET ###

    #
    # @report = {
    #   title: 'Master Ticker List',
    #   last_updated: Time.current.in_time_zone("US/Eastern").strftime('%Y-%m-%d %H:%M:%S'),
    #   line_items: line_items,
    #   item_count: line_items.size,
    # }
    #
    render :industry_report
  end

  def mark_reviewed
    ReportReview.log_review(params[:report_type], params[:report_date])
  end

  def reviewed_reports
    @report = { lines: ReportReview.list_by_date(report_date) }
  end

private

  # I know biz logic shouldn't be in the controller but this is experimental. Will move to interactor later.
  def filter(items)
    return items unless params[:price] || params[:mclt] || params[:mcgt] || params[:default_filter]

    if params[:default_filter]
      @sort_field = [{field: :volume_ratio, direction: :desc}, {field: :week_52_streak, direction: :asc}]
      # @sort_field = [{field: :week_52_streak, direction: :asc}]
      return items
        .reject { |li| (li[:market_cap] || 0) < 700_000 } # market cap is in thousands
        # .reject { |li| (li[:week_52_streak] || 6).to_f > 5 }
    end

    items
      .reject { |li| params[:price] && (li[:last_trade] < params[:price].to_f) }
      .reject { |li| params[:mclt] && (li[:market_cap].nil? || (li[:market_cap] < (params[:mclt].to_f * 700_000_000))) }
      .reject { |li| params[:mcgt] && (li[:market_cap].nil? || (li[:market_cap] > (params[:mcgt].to_f * 700_000_000))) }
  end

  def report_date
    begin
      @report_date ||=
        if params[:report_date] =~ /\d{2}\/\d{2}\/\d{4}/
          Date.strptime(params[:report_date], '%m/%d/%Y')
        else
          Date.strptime(params[:report_date], '%Y%m%d')
        end
    rescue
      @report_date ||= DailyStockPrice.most_recent_date
    end
  end

  def run_query(qry, fields=nil)
    ReportPresenter.format(
      ActiveRecord::Base.connection.execute(qry),
      fields,
      sort_field: params[:sort_field].try(:to_sym) || :volume_ratio
    )
  end

  def set_vix_contango_reading
    @vix = VIXFuturesHistory.last
  end

  def sort_field
    @sort_field ||= params[:sort_field].try(:to_sym) || :volume_ratio
  end
end

app/helpers/report_helper.rb
module ReportHelper
  RJUST_FIELDS=[
    :last_trade,
    :change_percent,
    :percent_above_52_week_high,
    :gap_percent,
    :float,
    :float_percent_traded,
    :market_cap,
    :dividend_yield,
    :institutional_ownership_percent,
    :volume,
    :volume_ratio,
    :volume_average,
    :short_days_to_cover,
    :short_percent_of_float
  ]

  def link_to_report(page, report_date)
    s = link_to("Go to Report", send("reports_#{page}_path", report_date: report_date.strftime("%Y%m%d")))
    s.html_safe
  end

  def report_date_form(page, current_report_date)
    s = form_tag "/reports/#{page}", method: :get, authenticity_token: false do
      b = text_field_tag :report_date, current_report_date.strftime('%m/%d/%Y')
      b << submit_tag("Go")
      b
    end
    s.html_safe
  end

  def set_vix_contango_style(contango_percent)
    "background-color: red" if contango_percent < 1
  end

  # TODO move this method into the presenter
  def set_css_class(report, field)
    css_class = "monospaced "

    if report[:gray_symbol]
      css_class << "gray "
    else
      unless field == :index
        if report[:change_percent].to_f > 0
          css_class << "green "
        elsif report[:change_percent].to_f < 0
          css_class << "red "
        end

        if report[:gap_pct].to_f > 0
          css_class << "green "
        elsif report[:gap_pct].to_f < 0
          css_class << "red "
        end

        if report[:percent_above_52_week_high].present?
          css_class << "green "
        end

        if report[:percent_below_52_week_low].present?
          css_class << "red "
        end
      end
    end

    css_class << "rjust " if RJUST_FIELDS.include?(field)

    case field
      when :index
        if report[:sp500]
          css_class << 'orange-text'
        end
      when :percent_above_52_week_high
        if report[:percent_above_52_week_high].to_f > 5.0
          css_class << "darkgreen-bg  "
        end

        if report[:percent_above_52_week_high].to_f.abs > 7.5
          css_class << "bold "
        end

      when :change_percent
        if report[:change_percent].to_f < -7.5
          css_class << "darkred-bg  "
        elsif report[:change_percent].to_f > 7.5
          css_class << "darkgreen-bg  "
        end

        if report[:change_percent].to_f.abs > 10
          css_class << "bold "
        end
      when :gap_percent
        if report[:gap_pct].to_f < -7.5
          css_class << "darkred-bg  "
        elsif report[:gap_pct].to_f > 7.5
          css_class << "darkgreen-bg  "
        end

        if report[:gap_pct].to_f.abs > 10
          css_class << "bold "
        end
      when :float
        # Format how it is displayed into millions from thousands of shares
        # report[:float] = '%.0f' % (report[:float].to_f / 1000) if report[:float].present?

        # Have a different designator for low float stock
        # if (report[:float].to_f < 15 && (report[:float].to_f) > 0)
        #   css_class << 'gold-bg '
        # end
      when :float_percent_traded
        if report[:float_percent_traded].to_f > 75
          css_class << 'gold-bg '
        end

      when :volume_ratio then css_class << "yellow-bg " if (report[:volume_ratio].to_f > 3)
      when :range then css_class << "yellow-bg " if (report[:range].to_f > 7)
      when :unscrape then css_class << "clickable "

    end

    css_class.strip
  end

  def symbol_icon(symbol)
    image = $ticker_icon_categories[symbol]
    if image
      image_tag(asset_path(image), class: 'report-stock-icon')
    else
      ''
    end
  end

  def ticker_symbol(line_item)
    outside_52_wk_marker = line_item[:outside_52_week_range] ? content_tag(:span, " *", style: "color: orange") : ''

    link_to(
      "#{line_item[:ticker_symbol]}",
      "https://www.reuters.com/company/#{line_item[:ticker_symbol]}",
      # "https://old.nasdaq.com/symbol/#{line_item[:ticker_symbol].downcase}",
      target: '_blank'
    ) + outside_52_wk_marker + symbol_icon(line_item[:ticker_symbol])
  end
end

app/views/reports/_report_reviewed.slim
#review-notifier
  - if report_reviewed_date.present?
    = "✅ Reviewed #{report_reviewed_date.strftime('%m/%d/%y')}"
  - else
    =link_to("Mark Reviewed", reports_mark_reviewed_path(report_type: report_type, report_date: report_date.strftime("%Y%m%d")), class: 'button btn btn-default', remote: true, method: :patch)

app/views/reports/_report_table.html.haml
.report-container
  %table.table-bordered{ style: "width: 1000px;" }
    %thead
      %th#index{ style: "width: 25px;"}
      %th#ticker-symbol{ style: "width: 75px;"} Symbol
      -if fields.include?(:company_name)
        %th#company-name.rjust{ style: "width: 100px;"}
      %th#last-trade.rjust{ style: "width: 50px;"} Last
      -if fields.include?(:change_percent)
        %th#percent-change.rjust{ style: "width: 90px;"} % Change
      -if fields.include?(:gap_percent)
        %th#gap-percent.rjust{ style: "width: 90px;"} % Gap
      -if fields.include?(:percent_above_52_week_high)
        %th#percent-above-52-week-high.rjust{ style: "width: 90px;"} % 52+
      -if fields.include?(:volume)
        %th#volume.rjust.no-decoration{ style: "width: 100px"}= link_to('Volume (K)',request.env['PATH_INFO'] + '?sort_field=volume', style: 'color: #FFFFFF;')
      %th#average-volume.rjust{ style: "width: 100px;"} Avg Vol (K)
      -if fields.include?(:volume_ratio)
        %th#volume-ratio.rjust{ style: "width: 100px;"} Volume Ratio
      -if fields.include?(:short_days_to_cover)
        %th#short-days-to-cover.rjust.divider-left{ style: "width: 65px;"}= "Short<br />Ratio".html_safe
      -if fields.include?(:short_percent_of_float)
        %th#short-percent-of-float.rjust.divider-right{ style: "width: 65px;"}= "Short %<br />of Float".html_safe
      %th#float.rjust.divider-left{ style: "width: 65px;"} Float (M)
      %th#float-percent-traded.divider-right.rjust{ style: "width: 65px;"} Float %
      -if fields.include?(:market_cap)
        %th#mkt-cap.divider-right.rjust{ style: "width: 75px;"} MktCap(B)
      -if fields.include?(:dividend_yield)
        %th#dividend-yield.divider-right.rjust{ style: "width: 65px;"} Div %
      -if fields.include?(:institutional_ownership_percent)
        %th#institutional-ownership-percent.rjust{ style: "width: 65px;"} IO %
      -if fields.include?(:week_52_streak)
        %th#week-52-streak.rjust.divider-left{ style: "width: 65px;"}= "Streak".html_safe
      -if fields.include?(:days_active)
        %th#days-active.rjust.divider-right{ style: "width: 65px;"}= "Days Active".html_safe
      %th#actions{ style: "width: 100px; padding-left: 15px;"} Actions
    -report.each_with_index do |r, i|
      %tr{ id: r['ticker_symbol'] }
        %td{ class: set_css_class(r, :index)}= i+1
        %td{ class: set_css_class(r, :ticker_symbol) }= ticker_symbol(r).html_safe
        -if fields.include?(:company_name)
          %td{ class: set_css_class(r, :company_name) }= r[:company_name]
        %td{ class: set_css_class(r, :last_trade) }= r[:last_trade]
        -if fields.include?(:change_percent)
          %td{ class: set_css_class(r, :change_percent) }= r[:change_percent]
        -if fields.include?(:gap_percent)
          %td{ class: set_css_class(r, :gap_percent)}= r[:gap_percent]
        -if fields.include?(:percent_above_52_week_high)
          %td{ class: set_css_class(r, :percent_above_52_week_high)}= r[:percent_above_52_week_high]
        -if fields.include?(:volume)
          %td{ class: set_css_class(r, :volume) }= r[:volume]
        %td{ class: set_css_class(r, :volume_average) }= r[:volume_average]
        -if fields.include?(:volume_ratio)
          %td{ class: set_css_class(r, :volume_ratio) }= r[:volume_ratio]
        -if fields.include?(:short_days_to_cover)
          %td.divider-left{ class: set_css_class(r, :short_days_to_cover) }= r[:short_days_to_cover]
        -if fields.include?(:short_percent_of_float)
          %td.divider-right{ class: set_css_class(r, :short_percent_of_float) }= r[:short_percent_of_float]
        %td.divider-left{ class: set_css_class(r, :float) }= r[:float]
        %td.divider-right{ class: set_css_class(r, :float_percent_traded) }= r[:float_percent_traded]
        -if fields.include?(:market_cap)
          %td.divider-right{ class: set_css_class(r, :market_cap) }= r[:market_cap]
        -if fields.include?(:dividend_yield)
          %td.divider-right{ class: set_css_class(r, :dividend_yield) }= r[:dividend_yield]
        -if fields.include?(:institutional_ownership_percent)
          %td{ class: set_css_class(r, :institutional_ownership_percent) }= r[:institutional_ownership_percent]
        -if fields.include?(:week_52_streak)
          %td.divider-left.rjust{ class: set_css_class(r, :week_52_streak) }= r[:week_52_streak]
        -if fields.include?(:days_active)
          %td.divider-right.rjust{ class: set_css_class(r, :days_active) }= r[:days_active]
        %td{ class: set_css_class(r, :actions), style: "padding-left: 15px;" }= link_to("H", reports_hide_symbol_path(r[:ticker_symbol]), remote: true, method: :patch) + " " + link_to("U", reports_unscrape_symbol_path(r[:ticker_symbol]), remote: true, method: :patch)

app/views/reports/afterhours.html.haml
%h1 Afterhours

%h2 Gapping Up, By Average Volume

-if @report_volume_up.count > 0
  %div Last Updated: #{@report_volume_up.first[:updated_at].in_time_zone("US/Eastern")}
  %div Items: #{@report_volume_up.count}

.report_date_form
  =report_date_form :afterhours

=render partial: "report_table", locals: { report: @report_volume_up, report_name: "afterhours_volume_up", fields: @fields }

%h2 Gaps, No Afterhours Volume History

=render partial: "report_table", locals: { report: @report_percent, report_name: "afterhours_percent", fields: @fields }


%h2 Gapping Down, By Average Volume

=render partial: "report_table", locals: { report: @report_volume_down, report_name: "afterhours_volume_down", fields: @fields }

app/views/reports/earnings.html.haml
%h1 Earnings Calendar

.report_date_form
  =report_date_form :earnings

-@report.each do |report_group|

  %h2= "#{report_group[:earnings_date]} #{report_group[:before_after]}"

  =render partial: "report_table", locals: { report: report_group[:data], report_name: "earnings", fields: [:ticker_symbol, :company_name, :last_trade, :average_volume, :short_ratio, :float, :actions] }

app/views/reports/gaps.html.haml
%h1 Gap Up / Gap Down

%h2 Bullish Gaps

-if @report_bullgaps.count > 0
  %div Last Updated: #{@report_bullgaps.first['snapshot_time'] || @report_bullgaps.first['price_date']}

.report_date_form
  =report_date_form :gaps

=render partial: "report_table", locals: { report: @report_bullgaps, report_name: "bullgaps", fields: @fields }

%h2 Bearish Gaps

=render partial: "report_table", locals: { report: @report_beargaps, report_name: "bullgaps", fields: @fields }

app/views/reports/hammers.html.haml
%h1 Hammers and Dojis Report

-if @report.count > 0
  %div Last Updated: #{@report.first['quote_time']}
  %div Items: #{@report.count}


.report-container
  %table.table-bordered#hammers
    %thead
      %th#index
      %th#ticker-symbol Ticker Symbol
      %th#last-trade Last
      %th#pct_change %Chg
      %th#volume Volume (K)
      %th#average-volume Avg Vol (K)
      %th#volume-ratio Volume Ratio
      %th#float Float
      %th#hide{ style: "width: 100px;"} Hide
      %th#unscrape{ style: "width: 100px;"} Unscrape
    -@report.each_with_index do |r, i|
      %tr{ id: r['ticker_symbol'] }
        %td= i+1
        %td{ class: set_css_class(r, :ticker_symbol) }= r['ticker_symbol']
        %td{ class: set_css_class(r, :last_trade) }= r['last_trade']
        %td{ class: set_css_class(r, :pct_change) }= r['pct_change']
        %td{ class: set_css_class(r, :volume) }= r['volume']
        %td{ class: set_css_class(r, :average_volume) }= r['average_volume']
        %td{ class: set_css_class(r, :volume_ratio) }= r['volume_ratio']
        %td{ class: set_css_class(r, :float) }= r['float']
        %td{ class: set_css_class(r, :hide) }= link_to "H", reports_hide_symbol_path(r['ticker_symbol']), remote: true, method: :patch
        %td{ class: set_css_class(r, :unscrape) }= link_to "U", reports_unscrape_symbol_path(r['ticker_symbol']), remote: true, method: :patch

app/views/reports/ipo_list.html.haml
%h1 IPO list

-if @report.count > 0
  %div Items: #{@report.count}


.report-container
  %table.table-bordered#ipo_list{ style: "width: 700px;"}
    %thead
      %th#ticker-id ID
      %th#symbol{ style: "width: 100px;"} Ticker Symbol
      %th#symbol{ style: "width: 100px;"} Company Name
      %th#symbol{ style: "width: 100px;"} First Price Date
      %th#hide{ style: "width: 100px;"} Days
      %th#hide{ style: "width: 100px;"} Hide
      %th#unscrape{ style: "width: 100px;"} Unscrape
    -@report.each_with_index do |r, i|
      %tr{ id: r['ticker_symbol'] }
        %td= i+1
        %td{ class: set_css_class(r, :symbol) }= r['ticker_symbol']
        %td{ class: set_css_class(r, :company_name) }= r['company_name']
        %td{ class: set_css_class(r, :first_price_date) }= r['first_price_date']
        %td{ class: set_css_class(r, :first_price_date) }= r['days']
        %td{ class: set_css_class(r, :hide) }= link_to "H", reports_hide_symbol_path(r['ticker_symbol']), remote: true, method: :patch
        %td{ class: set_css_class(r, :unscrape) }= link_to "U", reports_unscrape_symbol_path(r['ticker_symbol']), remote: true, method: :patch

app/views/reports/mark_reviewed.js.erb
Turbolinks.visit(location.toString());

app/views/reports/range.html.haml
%h1 Big Range

-if @report.count > 0
  %div Last Updated: #{@report.first['quote_time']}
  %div Items: #{@report.count}

.report_date_form
  =report_date_form :big_range

.report-container
  %table.table-bordered#big-range{ style: "width: 900px;"}
    %thead
      %th#index
      %th#ticker-symbol{ style: "width: 100px;"} Ticker Symbol
      %th#last-trade{ style: "width: 100px;"} Last
      %th#pct_change{ style: "width: 100px;"} %Chg
      %th#pct_change_60day{ style: "width: 100px;" } Range %
      %th#volume{ style: "width: 100px;"} Volume (K)
      %th#average-volume{ style: "width: 100px;"} Avg Vol (K)
      %th#volume-ratio{ style: "width: 100px;"} Volume Ratio
      %th#float{ style: "width: 100px;"} Float
      %th#hide{ style: "width: 100px;"} Hide
      %th#unscrape{ style: "width: 100px;"} Unscrape
    -@report.each_with_index do |r, i|
      %tr{ id: r['ticker_symbol'] }
        %td= i+1
        %td{ class: set_css_class(r, :ticker_symbol) }= r['ticker_symbol']
        %td{ class: set_css_class(r, :last_trade) }= r['last_trade']
        %td{ class: set_css_class(r, :pct_change) }= r['pct_change']
        %td{ class: set_css_class(r, :range) }= r['range']
        %td{ class: set_css_class(r, :volume) }= r['volume']
        %td{ class: set_css_class(r, :average_volume) }= r['average_volume']
        %td{ class: set_css_class(r, :volume_ratio) }= r['volume_ratio']
        %td{ class: set_css_class(r, :float) }= r['float'].to_f.round(2)
        %td{ class: set_css_class(r, :hide) }= link_to "H", reports_hide_symbol_path(r['ticker_symbol']), remote: true, method: :patch
        %td{ class: set_css_class(r, :unscrape) }= link_to "U", reports_unscrape_symbol_path(r['ticker_symbol']), remote: true, method: :patch