config/routes.rb
StockTrendFinder::Application.routes.draw do
  resources :tweets
  resources :tickers
  resources :stocktwits, except: [:show]
  # Stocktwits AJAX calls
  post 'stocktwits/add_twit'        => 'stocktwits#add_twit'
  post 'stocktwits/edit_twit'       =>'stocktwits#edit_twit'
  post 'stocktwits/call_result'     => 'stocktwits#call_result'
  post 'stocktwits/hide'            => "stocktwits#hide"
  post 'stocktwits/load_twits'      => "stocktwits#load_twits"
  # post 'stocktwits/note'            => 'stocktwits#edit_note'
  get 'stocktwits/refresh'          => "stocktwits#refresh"
  get 'stocktwits/toggle_watching'  => "stocktwits#toggle_watching"
  get 'stocktwits/watching'         => "stocktwits#watching"

  namespace :reports do
    get 'active_stocks'
    get 'range'
    get 'premarket'
    get 'gaps'
    get 'afterhours'
    get 'earnings'
    get 'sma50_breaks'
    get 'sma200_breaks'
    get 'candle_row'
    get 'pctgainloss'
    get 'week52_highs'
    get 'week52_lows'
    get 'ticker_list'
    get 'ipo_list'
    get 'reviewed_reports'
    patch 'mark_reviewed'
  end
  patch 'reports/hide/:symbol(.:format)', to: 'reports#hide_symbol', as: 'reports_hide_symbol'
  patch 'reports/unscrape/:symbol(.:format)', to: 'reports#unscrape_symbol', as: 'reports_unscrape_symbol'
  post 'tickers/:ticker/note', to: 'tickers#note', as: 'tickers_note'

  namespace :tda_data do
    post 'watchlists/symbol', to: 'watchlists#add_symbol', as: 'watchlists_add_symbol'
  end

  root 'home#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stock Trend Finder
    = stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    :javascript
      $(function() {
          $( "#report_date" ).datepicker();
        });

    :javascript
      setTimeout(function(){
        window.location.reload(1);
      }, 300000);

  %body
    %nav.navbar.navbar-default{ role: "navigation" }
      .container
        %ul.nav.navbar-nav
          %li.active= link_to "Pre", reports_premarket_path
          %li.active= link_to "Gaps", reports_gaps_path
          %li.active= link_to "52+", reports_week52_highs_path
          %li.active= link_to "52-", reports_week52_lows_path
          %li.active= link_to "Active", reports_active_stocks_path
          %li.active= link_to "After", reports_afterhours_path
          -#%li.active= link_to "Range", reports_range_path
          -#%li.active= link_to "200DMA", reports_sma200_breaks_path
          -#%li.active= link_to "4-candle", reports_candle_row_path
          %li.active= link_to "10% g/l", reports_pctgainloss_path
          %li.active= link_to "Tickers", reports_ticker_list_path
          %li.active= link_to "Reviews", reports_reviewed_reports_path
          -#%li.active= link_to "IPO", reports_ipo_list_path
    .container
      = yield

app/views/layouts/stocktwits.html.haml
!!!
%html
  %head
    %title StockTwits Archive
    = stylesheet_link_tag  "application", media: "all",  "data-turbolinks-track" => true
    = javascript_include_tag "application",  "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.stocktwits
    .container
      = yield